linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - contextcheck
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errcheck
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - forbidigo
  - forcetypeassert
  - funlen
  - gci
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - goerr113
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - ireturn
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - paralleltest
  - prealloc
  - predeclared
  - promlinter
  - revive
  - staticcheck
  - stylecheck
  - tagliatelle
  - tenv
  - testpackage
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  - wrapcheck
  disable:
  - cyclop
  - gochecknoglobals
  - gomnd
  - lll
  - nlreturn
  - rowserrcheck # https://github.com/golangci/golangci-lint/issues/264
  - sqlclosecheck # https://github.com/golangci/golangci-lint/issues/264
  - varnamelen
  - wastedassign # https://github.com/golangci/golangci-lint/issues/264
  - wsl

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-polyline)
  goimports:
    local-prefixes: github.com/twpayne/go-polyline

issues:
  exclude-rules:
  - linters:
    - scopelint
    path: "_test\\.go"
